# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/porsche/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),porsche)

$(call add-radio-file-sha1-checked,radio/abl.img,84d30bda1e8136bdc3bd52722ae55d6ca7d2d2fe)
$(call add-radio-file-sha1-checked,radio/aop.img,daef289ff3781fefdaf8235f163fb837e979d67c)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,d37a66f1fc9aeb57558cfed07276b0285378cd34)
$(call add-radio-file-sha1-checked,radio/cpucp.img,e15f6c86ea87e0017a652de27cc6fa3da3c9c839)
$(call add-radio-file-sha1-checked,radio/devcfg.img,48a276712a4ec5f63ad66f964c4283e99eb1fb01)
$(call add-radio-file-sha1-checked,radio/dsp.img,634718247c9670c0c2aab842804ea74c3f274396)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,0d84380e52e98ff4b3f2584abf6e3d0380838616)
$(call add-radio-file-sha1-checked,radio/hyp.img,81428b54c49bb9235f487815a9c85419275122e7)
$(call add-radio-file-sha1-checked,radio/imagefv.img,21b59edd1d8311107a93e994ec15f4ba8e34294f)
$(call add-radio-file-sha1-checked,radio/keymaster.img,16def9d1492560f784336e56679fc2a7132440bb)
$(call add-radio-file-sha1-checked,radio/modem.img,59c12baf7a3019f33b4727b74ebeee0f33a7d362)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,7b2631665099e7fbf451b4d8c84e1a9198fb8600)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,bcd981d0d975e649c1b4d2a741ee0bce1ca905bb)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,86e09de277f4a8a9723f33839024401957110dc2)
$(call add-radio-file-sha1-checked,radio/qupfw.img,ac5bcf41462e1a45a3759db904b64ec76dc97253)
$(call add-radio-file-sha1-checked,radio/qweslicstore.img,180cf2903b9872499d05eeef08c472575fa3225e)
$(call add-radio-file-sha1-checked,radio/shrm.img,7c1f3b66663c71d940d332511492ceefe98c201d)
$(call add-radio-file-sha1-checked,radio/splash.img,d316941bfde9cc9180158fdafab46dd04310e81d)
$(call add-radio-file-sha1-checked,radio/tz.img,5d6d2cb74c2d1edc2cc62e4bcbd4e92fbb1830a4)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,8cc22eeccd728409f5cc9a15d6bf2c282ae7b69f)
$(call add-radio-file-sha1-checked,radio/xbl.img,4f98ae209e080c59172aaf6be0163ec3b508823f)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,6807eb70fa77c428aedd5ee257f09e8bb957824e)

endif
