# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/porsche/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),porsche)

$(call add-radio-file-sha1-checked,radio/abl.img,34e6753f3e081ed9ae7d130913555e67bac5e4d9)
$(call add-radio-file-sha1-checked,radio/aop.img,b6d5b57f34398b3bb53b377c3546c4bbce6f3b1c)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,9302b1c9fb9e8e2e7a467a691923d943872b4a5c)
$(call add-radio-file-sha1-checked,radio/cpucp.img,5d3bcfbffddadf28fe67f51b797e1c0d4f8abeb8)
$(call add-radio-file-sha1-checked,radio/devcfg.img,4292c05c5e49edbec60f002df04505242408767b)
$(call add-radio-file-sha1-checked,radio/dsp.img,634718247c9670c0c2aab842804ea74c3f274396)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,bdbe03166f33a9ffef9b381346f04bed3c0fdc4b)
$(call add-radio-file-sha1-checked,radio/hyp.img,6e5b3065f31a97721f8631bca2b8bffa028a6d03)
$(call add-radio-file-sha1-checked,radio/imagefv.img,eb095af5b161702b4777c4e4058b79d55658ee06)
$(call add-radio-file-sha1-checked,radio/keymaster.img,7b4a74087d8f83a80028f266233ad1df88380986)
$(call add-radio-file-sha1-checked,radio/modem.img,ba65de981cd50166c0c66055c9655cb0a5386caf)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,2ff04b2ff842ff98d8d1366ccff47368196f029a)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,bcd981d0d975e649c1b4d2a741ee0bce1ca905bb)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,4ca9e5d4aa3e73ffed5491fd7911f967034e9530)
$(call add-radio-file-sha1-checked,radio/qupfw.img,31b5f86dad4e76809285b94b88f53180d5128f02)
$(call add-radio-file-sha1-checked,radio/qweslicstore.img,180cf2903b9872499d05eeef08c472575fa3225e)
$(call add-radio-file-sha1-checked,radio/shrm.img,30a53b58357f8b6514b1754a436ed0c452a786f7)
$(call add-radio-file-sha1-checked,radio/splash.img,d316941bfde9cc9180158fdafab46dd04310e81d)
$(call add-radio-file-sha1-checked,radio/tz.img,6a7834adca6ba39a7d9ca08e1a232bd740a44a59)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,f51ca427ddb46b38c4c8b901dad007d765d957b5)
$(call add-radio-file-sha1-checked,radio/xbl.img,6292a0c921763a41b4fdf89a094e92cca79850dd)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,104d8fa6e24b80d301b29d9f0906e41cef52ec6a)

endif
