# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/porsche/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),porsche)

$(call add-radio-file-sha1-checked,radio/abl.img,6ada6a34d4affc84a9e9c247b28ac8286de07133)
$(call add-radio-file-sha1-checked,radio/aop.img,523566f125649ca116f23e1603ec764d5a2afac8)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,0e990f22f62dbd2dfcdcc1f043a7141d81b4af00)
$(call add-radio-file-sha1-checked,radio/cpucp.img,671186b1249f61861c1e6c4ab94cb4bf5edd56d3)
$(call add-radio-file-sha1-checked,radio/devcfg.img,c6785b3d9b03dd0946aef32c68ed1fea625081fa)
$(call add-radio-file-sha1-checked,radio/dsp.img,634718247c9670c0c2aab842804ea74c3f274396)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,ff6bdd1be10a12266e624c4927f95c040b7fa60b)
$(call add-radio-file-sha1-checked,radio/hyp.img,5c2f419ed3dc296ff21bdef57554f01eb22e6b82)
$(call add-radio-file-sha1-checked,radio/imagefv.img,b298471e0e6081c9434fbb1e6480797e463cdb81)
$(call add-radio-file-sha1-checked,radio/keymaster.img,170f7c14dd1fa559d91af251b2b01ec521b4b334)
$(call add-radio-file-sha1-checked,radio/modem.img,09814bdab12b337ab5e452f7e1df376c9a1a97cd)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,9726cd1ddd4cd49a90c4bd0f4251582af7305359)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,bcd981d0d975e649c1b4d2a741ee0bce1ca905bb)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,a8e4ed6cb631bb2a1fa5c92b268dc2f17eaa574b)
$(call add-radio-file-sha1-checked,radio/qupfw.img,673abeff436e3220873200d2e7c3ba3a0e4e42c8)
$(call add-radio-file-sha1-checked,radio/qweslicstore.img,180cf2903b9872499d05eeef08c472575fa3225e)
$(call add-radio-file-sha1-checked,radio/shrm.img,041b28c3678f8bb37714bdac5cee394fba019b0c)
$(call add-radio-file-sha1-checked,radio/splash.img,d316941bfde9cc9180158fdafab46dd04310e81d)
$(call add-radio-file-sha1-checked,radio/tz.img,112c868c64b2890a9ed1d96586942d6ff2544c70)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,fedfd3de3ff5c5a0770a3c241a492939eea5be35)
$(call add-radio-file-sha1-checked,radio/xbl.img,c1105b55d84b51821be14423b3f04ebab0360895)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,22263fbe187b0dd701971a94bf120e1372a94909)

endif
